name: Update File on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR status
        if: github.event.pull_request.merged == true
        run: |
          # Add your script or commands here to update the specific file.
          # For example, you can use the GitHub API or other tools to modify the file.
      - name: Commit and Push Changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git checkout -b update-file
          git commit -m "Update file on PR merge"
          git push origin update-file
